config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?
  mount Blacklight::Engine => '/'

    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  if Rails.env.production? || Rails.env.stage?
    devise_for :users, controllers: { omniauth_callbacks: "omniauthcallbacks" }, skip: [:sessions]
    devise_scope :user do
      post 'sign_in', to: 'omniauth#new', as: :new_user_session
      post 'sign_in', to: 'omniauth_callbacks#shibboleth', as: :new_session
      get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    end
  else
    devise_for :users
  end
  
  mount Hydra::RoleManagement::Engine => '/'

  mount Qa::Engine => '/authorities'
  mount Hyrax::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'hyrax/homepage#index'
  curation_concerns_basic_routes
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get '/imageviewer/:id', to: 'hyrax/images#advanced', constraints: { id: /.*/ }, as: 'imageviewer'
  get '/impersonate_user', to: 'impersonates#index'
  get '/impersonate/:id', to: 'impersonates#impersonate', constraints: { id: /.*/ }, as: :impersonate
  get '/stop_impersonating', to: 'impersonates#stop_impersonating', as: :stop_impersonating

  # Adding copy method to collections
  scope module: 'hyrax' do
    get '/collections/copy/:id', controller: 'collections', action: :copy
    get '/collections/dl_powerpoint/:id', controller: 'collections', action: :dl_powerpoint, :defaults => { :format => 'pptx' }
    get '/collections/dl_pdf/:id', controller: 'collections', action: :dl_pdf, :defaults => { :format => 'pdf' }

    namespace :dashboard do
      get '/collections/copy/:id', controller: 'collections', action: :copy
      get '/collections/upgrade/:id', controller: 'collections', action: :upgrade
      get '/collections/dl_powerpoint/:id', controller: 'collections', action: :dl_powerpoint, :defaults => { :format => 'pptx' }
      get '/collections/dl_pdf/:id', controller: 'collections', action: :dl_pdf, :defaults => { :format => 'pdf' }
      post '/collections/update_work_order/:id/:page/:per_page', controller: 'collections', action: :update_work_order
      post '/collections/update_subcollection_order/:id', controller: 'collections', action: :update_subcollection_order
    end
  end

  post '/update_top_level_course_collection', controller: 'top_level_collection_orders', action: :set_course_order
  post '/update_top_level_personal_collection/:id', controller: 'top_level_collection_orders', action: :set_personal_order

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/hyrax/collections_controller.rb
require_dependency Hyrax::Engine.root.join('app', 'controllers', 'hyrax', 'collections_controller').to_s

module Hyrax
  class CollectionsController < ApplicationController
    include TuftsCollectionControllerBehavior
  end
end

app/controllers/hyrax/dashboard/collection_members_controller.rb
require_dependency Hyrax::Engine.root.join('app', 'controllers', 'hyrax', 'dashboard', 'collection_members_controller').to_s

# Patching to include updating the work order after items are added to a collection
module Hyrax
  module Dashboard
    class CollectionMembersController < Hyrax::My::CollectionsController

      # Overwrite to add the new images to the collection's work order
      def after_update
        collection.update_order(collection.work_order | batch_ids, :work)

        if(not_from_drag_n_drop)
          respond_to do |format|
            format.html { redirect_to success_return_path, notice: t('hyrax.dashboard.my.action.collection_update_success') }
            format.json { render json: @collection, status: :updated, location: dashboard_collection_path(@collection) }
          end
        end
      end

      private

        # Checks the params to see if the request is from drag and drop in search results
        def not_from_drag_n_drop
          params[:origin].blank? || params[:origin] != "dragndrop"
        end

        # Overwrite to send errors to home page instead of dashboard
        def err_return_path
          root_path
        end
    end
  end
end

app/controllers/hyrax/dashboard/collections_controller.rb
require_dependency Hyrax::Engine.root.join('app', 'controllers', 'hyrax', 'dashboard', 'collections_controller').to_s

module Hyrax
  module Dashboard
    ## Shows a list of all collections to the admins
    class CollectionsController < Hyrax::My::CollectionsController
      include TuftsCollectionControllerBehavior
      with_themed_layout '1_column'

      ##
      # Overwrites collection create method to add various customizations for trove.
      def create
        # Manual load and authorize necessary because Cancan will pass in all
        # form attributes. When `permissions_attributes` are present the
        # collection is saved without a value for `has_model.`
        @collection = ::Collection.new
        authorize! :create, @collection
        # Coming from the UI, a collection type gid should always be present.  Coming from the API, if a collection type gid is not specified,
        # use the default collection type (provides backward compatibility with versions < Hyrax 2.1.0)
        @collection.collection_type_gid = params[:collection_type_gid].presence || default_collection_type.gid
        @collection.attributes = collection_params.except(:members, :parent_id, :collection_type_gid)
        @collection.assign_attributes({'displays_in' => ['trove']}) # Added for Trove
        @collection.apply_depositor_metadata(current_user.user_key)
        add_members_to_collection unless batch.empty?
        @collection.visibility = @collection.collection_type_gid == helpers.course_gid ?
          Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC :
          Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE # Changed for Trove
        if @collection.save
          after_create
        else
          after_create_error
        end
      end

      def destroy
        unless(is_personal_collection?(@collection))
          Rails.cache.delete 'views/collections-sidebar-courses'
        end
        Tufts::ExportManagerService.delete_all_assets(@collection)
        if @collection.destroy
          after_destroy(params[:id])
        else
          after_destroy_error(params[:id])
        end
      end

      ##
      # @function
      # Overwrites collection after_create callback to redirect to root, instead of dashboard.
      def after_create
        form
        set_default_permissions
        unless(is_personal_collection?(@collection)) 
          Rails.cache.delete 'views/collections-sidebar-courses'
        end
        # if we are creating the new collection as a subcollection (via the nested collections controller),
        # we pass the parent_id through a hidden field in the form and link the two after the create.
        link_parent_collection(params[:parent_id]) unless params[:parent_id].nil?
      
        respond_to do |format|
          ActiveFedora::SolrService.instance.conn.commit
          format.html { redirect_to root_path, notice: t('hyrax.dashboard.my.action.collection_create_success') } #Changed for trove
          format.json { render json: @collection, status: :created, location: root_path(@collection) }
        end
      end

      ##
      # Creates a Course Collection copy of a Personal Collection. Only for admin use.
      def upgrade
        unless(is_personal_collection?(@collection))
          redirect_to root_path, notice: t('trove_collections.additional_actions.notices.not_personal_collection')
        end
        Rails.cache.delete 'views/collections-sidebar-courses'
        new_collection = create_copy('course')
        ActiveFedora::SolrService.instance.conn.commit

        set_permissions(new_collection)
        copy_images_and_order(new_collection)

        redirect_to root_path, notice: t('trove_collections.additional_actions.notices.upgrade_success')
      end

      ##
      # Overwriting to redirect to home page, instead of dashboard.
      def after_destroy(_id)
        respond_to do |format|
          format.html do
            # Changed for Trove
            redirect_to root_path, notice: t('hyrax.dashboard.my.action.collection_delete_success')
          end
          format.json { head :no_content, location: root_path }
        end
      end

      ##
      # Responds to an ajax call and updates the work order
      def update_work_order
        per_page = params[:per_page] == 'null' ? blacklight_config.default_per_page : params[:per_page].to_i
        page = params[:page] == 'null' ? 1 : params[:page].to_i

        number_of_works = ActiveFedora::Base.where("member_of_collection_ids_ssim:#{@collection.id} AND has_model_ssim:Image").count
        # we're only updating a page at time in theory so get the subset of the array we're updating
        items_to_update = JSON.parse(params[:order])

        full_collection_order = @collection.work_order

        # number of items in this update
        number_to_update = items_to_update.length

        # the starting offset of the page to merge this is into the overall array
        initial_offset = page == 1 ? 0 : (page - 1) * per_page

        # the ending offset of the page to merge this into the array corrected for the end of the collection
        ending_offset = page * per_page > number_of_works ? number_of_works : page * per_page

        #update the overall collection
        full_collection_order[initial_offset,ending_offset] = items_to_update

        @collection.update_order(full_collection_order, :work)

        #Delete pdfs and ppts for this collection
        Tufts::ExportManagerService.delete_all_assets(@collection)
      end

      ##
      # Responds to an ajax call and updates the subcollection order
      def update_subcollection_order
        new_order = JSON.parse(params[:order])
        @collection.update_order(new_order, :subcollection) unless new_order.blank?
      end

      private

      ##
      # Overwritten to remove ids from CollectionOrder as well.
      def remove_members_from_collection
        batch.each do |pid|
          work = ActiveFedora::Base.find(pid)
          work.member_of_collections.delete @collection
          work.save!

          remove_id_from_work_order(pid)
        end
      end

      ##
      # Removes an id from the collection's work order
      # @param {str} id
      #   The id to remove from the order
      def remove_id_from_work_order(id)
        order = @collection.work_order
        return if order.blank?
        new_order = order - [id]
        @collection.update_order(new_order, :work) unless new_order == order
      end
    end
  end
end

app/controllers/hyrax/dashboard/nest_collections_controller.rb
# Patching to use our NestCollectionForm instead of Hyrax's
require_dependency Hyrax::Engine.root.join('app', 'controllers', 'hyrax', 'dashboard', 'nest_collections_controller').to_s

module Hyrax
  module Dashboard
    class NestCollectionsController < ApplicationController
      self.form_class = Tufts::Forms::Dashboard::NestCollectionForm # Adding tufts form
    end
  end
end

app/views/hyrax/dashboard/collections/_collection_title.html.erb
<% #@file Removed visibility badge %>
<% id = presenter.id %>

<section class="collection-title-row-wrapper"
  data-source="my"
  data-id="<%= id %>"
  data-colls-hash="<%= presenter.available_parent_collections(scope: controller) %>"
  data-post-url="<%= hyrax.dashboard_create_nest_collection_within_path(id) %>"
  data-post-delete-url="<%= hyrax.dashboard_collection_path(id) %>">

    <div class="collection-title-row-content">
      <h3 class="collection-title">
        <% # List multiple titles %>
        <% presenter.title.each_with_index do |title, index| %>
          <span><%= title %></span>
        <% end %>
      </h3>
      <%= presenter.collection_type_badge %>
    </div>
    <div class="collection-title-row-content">
      <%= render 'show_actions', presenter: presenter %>
    </div>
</section>

app/views/hyrax/dashboard/collections/_form.html.erb
<div class="panel panel-default tabs" id="collection-edit-controls">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active">
      <a href="#description" role="tab" data-toggle="tab"><%= t('.tabs.description') %></a>
    </li>
    <% if @form.persisted? %>
      <% if @collection.brandable? %>
        <li>
          <a href="#branding" role="tab" data-toggle="tab"><%= t('.tabs.branding') %></a>
        </li>
      <% end %>
      <% if @collection.discoverable? %>
        <li>
          <a href="#discovery" role="tab" data-toggle="tab"><%= t('.tabs.discovery') %></a>
        </li>
      <% end %>
    <% end %>
  </ul>

  <%= simple_form_for @form, url: [hyrax, :dashboard, @form], html: {class: 'editor'} do |f| %>
    <div class="tab-content">
      <div id="description" class="tab-pane active">
        <div class="panel panel-default labels">
          <div class="panel-body">

            <div id="base-terms">
              <% f.object.primary_terms.each do |term| %>
                <%= render_edit_field_partial(term, f: f) %>
              <% end %>

              <% if f.object.persisted? %>
                <%# we're loading these values dynamically to speed page load %>
                <%= f.input :thumbnail_id,
                            input_html: {data: {text: f.object.thumbnail_title}} %>
              <% end %>
            </div>
            <%= hidden_field_tag :type, params[:type] %>
            <%= hidden_field_tag :stay_on_edit, true %>
            <%= hidden_field_tag :collection_type_gid, @collection.collection_type_gid %>
            <!-- parent_id may be passed from the nested collections controller to allow a subcollection relationship to be added as collection is created -->
            <% if params[:parent_id].present? %>
              <%= hidden_field_tag :parent_id, params[:parent_id] %>
            <% end %>
            <% if params[:batch_document_ids].present? %>
              <% params[:batch_document_ids].each do |batch_item| %>
                <input type="hidden" name="batch_document_ids[]" value="<%= batch_item %>"/>
              <% end %>
            <% end %>
          </div>
        </div>
      </div> <!-- end description -->

      <% if @form.persisted? %>
        <div id="branding" class="tab-pane">
          <div class="panel panel-default labels">
            <div class="panel-body">
              <%= render 'form_branding', f: f %>
            </div>
          </div>
        </div>

        <div id="discovery" class="tab-pane">
          <div class="panel panel-default labels">
            <div class="panel-body">
              <%= render 'form_discovery', f: f %>
            </div>
          </div>
        </div>

      <% end %>

      <div class="panel-footer">
        <% if @collection.persisted? %>
          <%= f.submit t(:'hyrax.collection.select_form.update'), class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "update_submit", name: "update_collection" %>
          <%= link_to t(:'helpers.action.cancel'), hyrax.dashboard_collection_path(@collection), class: 'btn btn-link' %>
        <% else %>
          <%= f.submit t(:'hyrax.collection.select_form.create'), class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "create_submit", name: "create_collection" %>
          <%= link_to t(:'helpers.action.cancel'), root_path, class: 'btn btn-link' %>
        <% end %>
      </div>
    </div> <!-- end tab-content -->
  <% end # simple_form_for %>

</div> <!-- end collection-controls -->

app/views/hyrax/dashboard/collections/_form_discovery.html.erb
<div class="set-access-controls">

  <p><%= t('.para1') %></p>
  <p><%= t('.para2') %></p>

  <div class="form-group">
    <label class="radio">
      <input type="radio" id="visibility_open" name="<%= f.object_name %>[visibility]" value="<%= Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC %>" <% if @collection.open_access? %> checked="true"<% end %> /><strong><%= t('hyrax.visibility.authenticated.text', institution: institution_name) %></strong> - <%= t('hyrax.visibility.authenticated.note_html', institution: institution_name) %>
    </label>
    <label class="radio">
      <input type="radio" id="visibility_restricted" name="<%= f.object_name %>[visibility]" value="<%= Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE %>" <% if @collection.private_access? %> checked="true"<% end %> /><strong><%= t('hyrax.visibility.restricted.text') %></strong>- <%= t('hyrax.visibility.restricted.note_html') %>
    </label>
  </div>

</div>

app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
<div role="dialog" class="modal collection-list-modal fade" id="collection-list-container" tabindex="-1" aria-labelledby="col_add_title">
  <div class="modal-dialog text-left">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <span class="modal-title" id="col_add_title"><%= t("hyrax.collection.select_form.title") %></span>
        </div>
        <div class="modal-body">
          <% if user_collections.blank? %>
            <em> <%= t("hyrax.collection.select_form.no_collections") %></em><br /><br /><br /><br />
          <% else %>
          <div>
            <input placeholder="<%= current_user.admin? ? 'Search for collection by title' : 'Filter list of collections' %>" type="text" id="search" name="search" style="margin: 20p; width: 400px;" onkeyup="filter_options(this.value);"/>
          </div>
            <div class="collection-list">
              <fieldset>
                <legend><%= t("hyrax.collection.select_form.select_heading") %></legend>
              <ul id="select">
                 <% user_collections.sort { |c1,c2| c1['title_tesim'].first.upcase.gsub(/\A\p{Space}*/, '') <=> c2['title_tesim'].first.upcase.gsub(/\A\p{Space}*/, '') }.each_with_index  do |collection,index| %>
                  <li class="col-name" style="<%= current_user.admin? ? 'display:none' : 'display:list-item' %>">
                    <% selected = (collection.id == @add_works_to_collection) || (@add_works_to_collection.blank? && index == 0) %>
                    <%= radio_button_tag(:id, collection.id, selected, class: "collection-selector") %>
                    <% depositor = current_user.admin? ? (" - " + collection.depositor) : "" %>
                    <%= label_tag(:collection, "#{collection.title_or_label} (#{collection_type_label(collection.collection_type_gid)}#{depositor})", for: "id_#{collection.id}") %>
                  </li>
                <% end %>
              </ul>
              </fieldset>
            </div><!-- collection-list -->
          <% end %> <!-- else -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t("hyrax.collection.select_form.close") %></button>
          <% if user_collections.blank? %>
            <%= render 'hyrax/dashboard/collections/button_create_collection', label: t("hyrax.collection.select_form.create") %>

          <% else %>
            <%= render 'hyrax/dashboard/collections/button_for_update_collection', label: t("hyrax.collection.select_form.update"), collection_id: 'collection_replace_id' %>
            <%= render 'hyrax/dashboard/collections/button_create_collection', label: t("hyrax.collection.select_form.create_new") %>
          <% end %>
        </div>
      </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/hyrax/dashboard/collections/_show_actions.html.erb
<% #@file  Removing the Add to Collection button %>
<h2 class="sr-only"><%= t('hyrax.collection.actions.header') %></h2>
<div class="dropdown tufts-action-button">
  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
    <span class="sr-only" data-search-element="label"><%= t("trove_collections.additional_actions.label") %></span>
    <span aria-hidden="true"><%= t("trove_collections.additional_actions.label") %></span>
    <span class="caret"></span>
  </button>

  <ul class="dropdown-menu pull-right">
    <li>
      <%= link_to t("trove_collections.additional_actions.copy"),
                  "copy/#{@collection.id}",
                  class: 'copy-collection',
                  data: { turbolinks: false }
      %>
    </li>
    <% if(@collection.member_work_ids.count > 0) %>
      <li>
        <%= link_to t("trove_collections.additional_actions.pdf"),
                    "dl_pdf/#{@collection.id}",
                    class: 'download-pdf',
                    data: {
                        turbolinks: false,
                        confirm: t('copyright_acknowledgement.value')
                    }
        %>
      </li>
      <li>
        <%= link_to t("trove_collections.additional_actions.powerpoint"),
                    "dl_powerpoint/#{@collection.id}",
                    class: 'download-ppt',
                    data: {
                        turbolinks: false,
                        confirm: t('copyright_acknowledgement.value')
                    }
        %>
      </li>
    <% end %>
    <% if is_personal_collection?(@collection) && current_user.admin? %>
      <li>
        <%= link_to t("trove_collections.additional_actions.upgrade"),
                    "upgrade/#{@collection.id}",
                    class: 'upgrade-collection',
                    data: { turbolinks: false } %>
      </li>
    <% end %>
  </ul>
</div>
<% if can? :edit, presenter.solr_document %>

    <%= link_to t('trove_collections.additional_actions.edit_metadata.label'), # Changed button text to be more precise
                hyrax.edit_dashboard_collection_path(presenter),
                title: t('trove_collections.additional_actions.edit_metadata.desc'), # Changed button text to be more precise
                class: 'btn btn-primary' %>
<% end %>

<% if can? :destroy, presenter.solr_document %>
    <%= link_to t('hyrax.collection.actions.delete.label'),
                hyrax.dashboard_collection_path(presenter),
                title: t('hyrax.collection.actions.delete.desc'),
                class: 'btn btn-danger',
                data: { confirm: t('hyrax.collection.actions.delete.confirmation'),
                        method: :delete } %>
<% end %>
<%= link_to t('cancel'), collection_path(@collection), class: 'margin-left', data: { turbolinks: false } %>

app/views/hyrax/dashboard/collections/_show_document_list.html.erb
<% #@file  Removed visibility row from table %>

<table class="table table-striped collections-list-table collection-works-table">
  <caption class="sr-only">List of items in this collection</caption>
  <thead>
  <tr>
    <th>&nbsp;</th>
    <th class="title-column">Title</th>
    <th>Date added</th>
    <th>Owner</th>
    <% if current_user %>
      <th>Action</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <%= render partial: 'show_document_list_row', collection: documents, as: :document %>
  </tbody>
</table>

app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb
<% #@file  Removed visibility row from table %>

<% id = document.id %>
<tr id="document_<%= id %>">
  <td>&nbsp;
    <% if current_user and document.depositor != current_user.user_key %>
      <i class="glyphicon glyphicon-share-alt" />
    <% end %>
  </td>
  <td>
    <div class="media">
      <%= link_to [main_app, document], class: "media-left" do %>
        <%= render_thumbnail_tag document, { class: "hidden-xs file_listing_thumbnail" }, { suppress_link: true } %>
      <% end %>
      <div class="media-body">
        <p class="media-heading">
          <strong><%= link_to document.title_or_label, [main_app, document], id: "src_copy_link#{id}", class: "#{'document-title' if document.title_or_label == document.label}" %></strong>
          <a href="#" class="small" title="Click for more details"><i id="expand_<%= id %>" class="glyphicon glyphicon-chevron-right"></i></a>
        </p>
      </div>
    </div>
  </td>
  <td class="text-center"><%= document.date_uploaded %> </td>
  <td class="text-center"></td>
  <% if current_user and can? :edit, @collection %>
    <td class="text-center">
      <%= button_for_remove_from_collection @collection, document, label: "Remove", btn_class: "btn-danger btn-xs" %>
    </td>
  <% end %>
</tr>
<tr id="detail_<%= id %>"> <!--  document detail"> -->
  <td colspan="6">
    <dl class="expanded-details row">
      <dt class="col-xs-3 col-lg-2">Creator:</dt>
      <dd class="col-xs-9 col-lg-4"><%= document.creator.to_a.to_sentence %></dd>
      <dt class="col-xs-3 col-lg-2">Depositor:</dt>
      <dd class="col-xs-9 col-lg-4"><%= link_to_profile document.depositor %></dd>
      <dt class="col-xs-3 col-lg-2">Edit Access:</dt>
      <dd class="col-xs-9 col-lg-10">
        <% if document.edit_groups.present? %>
          Groups: <%= document.edit_groups.join(', ') %>
          <br />
        <% end %>
        Users: <%= document.edit_people.join(', ') %>
      </dd>
    </dl>
  </td>
</tr>

app/views/hyrax/dashboard/collections/show.html.erb
<% provide :page_title, construct_page_title(@presenter.title) %>

<div class="editor-warning"><%= t('trove_collections.editor-warning') %></div>
<div class="collections-wrapper">
  <section class="panel panel-default collections-panel-wrapper admin-show-page">
    <div class="panel-heading">
      <%= render 'collection_title', presenter: @presenter %>
    </div>

    <div class="panel-body">
      <section>
        <div itemscope itemtype="http://schema.org/CollectionPage" class="row collection">
          <div class="col-sm-3 text-center">
              <%= render 'hyrax/collections/collection_media_display', presenter: @presenter %>
              <%= link_to t('.public_view_label'), collection_path(id: @presenter.id) %>
          </div>
          <div class="col-sm-9 collection-description-wrapper">
            <!-- Parent Collection(s) -->
            <% if @presenter.collection_type_is_nestable? && @presenter.total_parent_collections > 0 %>
                <h4><%= t('.parent_collection_header') %> (<%= @presenter.total_parent_collections %>)</h4>
                <section id="parent-collections-wrapper" class="parent-collections-wrapper">
                  <%= render 'hyrax/dashboard/collections/show_parent_collections', presenter: @presenter %>
                </section>
            <% end %>

            <!-- Collection Description(s) -->
            <section>
              <%= render 'hyrax/collections/collection_description', presenter: @presenter %>
            </section>

            <% unless has_collection_search_parameters? %>
              <%= render 'show_descriptions' %>
            <% end %>
          </div>
        </div>
      </section>

      <!-- Search results label -->

      <% if @members_count > 0 || @presenter.subcollection_count > 0 %>
          <div class="hyc-blacklight hyc-bl-title">
            <h2>
              <% if has_collection_search_parameters? %>
                  <%= t('hyrax.dashboard.collections.show.search_results') %>
              <% end %>
            </h2>
          </div>
      <% end %>

      <!-- Search bar -->
      <section class="collections-search-wrapper">
        <div class="row">
          <div class="col-sm-8">
            <%# TODO: leaving this as it was causes rerouting to the public show page. needs work %>
            <%= render 'hyrax/collections/search_form', presenter: @presenter, url: hyrax.dashboard_collection_path(@presenter.id) %>
          </div>
        </div>
      </section>

      <!-- Subcollections -->
      <% if @presenter.collection_type_is_nestable? %>
        <section id="sub-collections-wrapper" class="sub-collections-wrapper">
          <h4><%= t('.subcollection_count') %> (<%= @subcollection_count %>)</h4>
          <div class="row">
            <div class="col-md-7">
              <%= render 'subcollection_list', id: @presenter.id, collection: @subcollection_docs %>
            </div>
            <% unless has_collection_search_parameters? %>
              <div class="col-md-5">
                <%= render 'show_subcollection_actions', presenter: @presenter %>
              </div>
            <% end %>
          </div>
        </section>
      <% end %>

      <!-- Works -->
      <section class="works-wrapper">
        <h4><%= t('.item_count') %> (<%= @members_count %>)</h4>

        <%= render 'sort_and_per_page', collection: @presenter %>
        <%= render_document_index @member_docs %>
        <%= render 'hyrax/collections/paginate' %>
      </section>

    </div><!-- /panel-body -->
  </section><!-- /collections-panel-wrapper -->
</div><!-- /collections-wrapper -->

<% if @presenter.collection_type_is_nestable? && !has_collection_search_parameters? %>
  <%= render 'hyrax/my/collections/modal_add_to_collection', source: 'show' %>
  <%= render 'hyrax/my/collections/modal_add_subcollection', id: @presenter.id, source: 'show' %>
  <%= render 'hyrax/dashboard/collections/modal_parent_collection_remove_deny', source: 'show' %>
<% end %>

<% unless has_collection_search_parameters? %>
  <%= render '/shared/select_work_type_modal', create_work_presenter: @presenter.create_work_presenter if @presenter.draw_select_work_modal? %>
<% end %>